# Generated by Django 5.2.4 on 2025-12-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_generatedtestcase_execute'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='last_selected_fr_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of FR info IDs that were selected when test cases were generated'),
        ),
    ]
